apiVersion: v1
kind: Service
metadata:
  name: student-survey
  namespace: default
spec:
  selector:
    app: student-survey
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer